### PR TITLE
API for displaying other protections in the HUD

### PR DESCRIPTION
**Pull request by taikedz**
This change allows other mods to list their areas of influence in the areas HUD, by providing a handler registration API

Documentation is provided in a markdown file, original functionality for listing protected areas is unaffected.

### CODE REVIEW

**Comment by ShadowNinja** [comment]
This is interesting, I'm just wondering what use cases this would have.
  * There are some style issues (see the [Lua code style guidelines](http://dev.minetest.net/Lua_code_style_guidelines)), in particular there should be spaces after but not before commas, and `f=function()` should be `function f()`.
  * All of `detect_extra_protection` can just be merged into `getRegisteredProtections` since the former isn't used anywhere else and the latter does effectively nothing but call the former.
  * I don't like some of the unrelated code style changes.
  * `mod.conf` is good.
  * The `get_auth_handler` thing is intentional, otherwise `areas` won't work with custom authentication handlers (there's an API to use your own authentication backend, `minetest.auth_table` is specific to the default `auth.txt` backend).  Is there a reason you wanted to use the table directly?
  * The registration function should conform to the style of the rest of the API (i.e. `areas.register_hud_handler(handler_name)` -> `areas:registerHudHandler(handler)`).
  * Also, `handler_name` -> `handler` as above (you pass it a handler, not a handler's name).
  * `cunjunction` -> `conjunction`.

**Comment by taikedz** [comment]
Thanks for feedback, hopefully I have adjusted suitably now... thanks for the link to the style guide, never even thought to look for an overarching one.

Use case is as referenced for tenplus1's protector-redo: I have a server, and know of another, where both `protector` and `areas` are on at the same time, and displaying protection names in the HUD has been desirable.

Similarly, I'd also like to add `pvp_areas` to the HUD https://github.com/taikedz/everamzah-pvp_areas/ as well as adding a hook into `mg_villages` https://github.com/Sokomine/mg_villages.

And any other reason to have info displayed in the hud depending on location.

Conceivably, it may even make more sense to make a standalone mod for a name display HUD - but I also don't want to have display conflicts with `areas`....

**Comment by ShadowNinja** [comment]
Almost, I was thinking something more like [this](http://sprunge.us/MdfY?diff).  Does that look good to you?

I've already pushed the `mod.conf` addition.

**Comment by taikedz** [comment]
* Change to api.lua - OK that makes more sense
* Change to api.md - yeah OK
* Change to hud.lua ... why the change here? If anything it deviated from the standard style, and is harder to see what's going on now...?

**Comment by taikedz** [comment]
Anything you wanted me to adjust to enable the pull?

**Comment by ShadowNinja** [comment]
@taikedz: I just did it that way because it's a lot easier to make the fields optional that way instead of using `string.format`.
Nothing for you to do, I'll push it in a moment.

**Comment by ShadowNinja** [comment]
6080ff065ea89e899f356ba723ea2467b6d32ccb

**Pull request closed without merging**
