### PR TITLE
Add callbacks for area operations

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by SmallJoker** [comment]
Needs rebase.
The changes are good, but there could be made more out of it by handling the callback return value. For example: Return `true` to abort the action. That would also open some more possibilities for other mods.

**Comment by SmallJoker** [comment]
@rubenwardy Ping.

**Comment by Panquesito7** [comment]
This was already added in [1bbb997](https://github.com/minetest-mods/areas/commit/1bbb997c7a170b701159bc97bc6c6f16d896ec54).
I think this should be closed.

**Comment by SmallJoker** [comment]
Thanks.

**Pull request closed without merging**
